# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 627)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 5, 20, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.BodyLabel_output = BodyLabel(self.centralwidget)
        self.BodyLabel_output.setObjectName("BodyLabel_output")
        self.gridLayout.addWidget(self.BodyLabel_output, 7, 1, 1, 1)
        self.BodyLabel_switch = BodyLabel(self.centralwidget)
        self.BodyLabel_switch.setObjectName("BodyLabel_switch")
        self.gridLayout.addWidget(self.BodyLabel_switch, 5, 1, 1, 1)
        self.SwitchButton = SwitchButton(self.centralwidget)
        self.SwitchButton.setObjectName("SwitchButton")
        self.gridLayout.addWidget(self.SwitchButton, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.TitleLabel = TitleLabel(self.centralwidget)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 1, 1, 1)
        self.NavigationInterface = NavigationInterface(self.centralwidget)
        self.NavigationInterface.setObjectName("NavigationInterface")
        self.gridLayout.addWidget(self.NavigationInterface, 0, 0, 14, 1)
        self.PrimaryPushButton_Export = PrimaryPushButton(self.centralwidget)
        self.PrimaryPushButton_Export.setObjectName("PrimaryPushButton_Export")
        self.gridLayout.addWidget(self.PrimaryPushButton_Export, 10, 1, 1, 1)
        self.BodyLabel_md = BodyLabel(self.centralwidget)
        self.BodyLabel_md.setObjectName("BodyLabel_md")
        self.gridLayout.addWidget(self.BodyLabel_md, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEdit_md = LineEdit(self.centralwidget)
        self.LineEdit_md.setObjectName("LineEdit_md")
        self.horizontalLayout.addWidget(self.LineEdit_md)
        self.PushButton_md = PushButton(self.centralwidget)
        self.PushButton_md.setObjectName("PushButton_md")
        self.horizontalLayout.addWidget(self.PushButton_md)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LineEdit_output = LineEdit(self.centralwidget)
        self.LineEdit_output.setObjectName("LineEdit_output")
        self.horizontalLayout_3.addWidget(self.LineEdit_output)
        self.PushButton_output = PushButton(self.centralwidget)
        self.PushButton_output.setObjectName("PushButton_output")
        self.horizontalLayout_3.addWidget(self.PushButton_output)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 1, 1, 1)
        self.IndeterminateProgressBar = IndeterminateProgressBar(self.centralwidget)
        self.IndeterminateProgressBar.setObjectName("IndeterminateProgressBar")
        self.gridLayout.addWidget(self.IndeterminateProgressBar, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Converter"))
        self.BodyLabel_output.setText(_translate("MainWindow", "Output File Path"))
        self.BodyLabel_switch.setText(_translate("MainWindow", "Modify the source file"))
        self.TitleLabel.setText(_translate("MainWindow", "Standard Markdown Export"))
        self.PrimaryPushButton_Export.setText(_translate("MainWindow", "Export"))
        self.BodyLabel_md.setText(_translate("MainWindow", "Markdown File Path"))
        self.PushButton_md.setText(_translate("MainWindow", "Browse"))
        self.PushButton_output.setText(_translate("MainWindow", "Browse"))
from qfluentwidgets import BodyLabel, IndeterminateProgressBar, LineEdit, NavigationInterface, PrimaryPushButton, PushButton, SwitchButton, TitleLabel
